"""add pgvector extension and ensure embedding column

Revision ID: a541755a590a
Revises: 001a7c65c912
Create Date: 2026-08-20 18:47:29.760205
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a541755a590a'
down_revision: Union[str, Sequence[str], None] = '001a7c65c912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_attachments', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('issue_attachments', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.add_column('issue_attachments', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('issue_attachments', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('issue_attachments', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.add_column('issue_attachments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'issue_attachments', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_attachments', type_='foreignkey')
    op.drop_column('issue_attachments', 'created_at')
    op.drop_column('issue_attachments', 'uploaded_by')
    op.drop_column('issue_attachments', 'mime_type')
    op.drop_column('issue_attachments', 'file_size')
    op.drop_column('issue_attachments', 'file_path')
    op.drop_column('issue_attachments', 'filename')
    # ### end Alembic commands ###
