"""add_troubleshooting_session_tables

Revision ID: ea9f8fe8bc23
Revises: 1ab9eeb7bf93
Create Date: 2026-08-30 10:41:42.180342
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'ea9f8fe8bc23'
down_revision: Union[str, Sequence[str], None] = '1ab9eeb7bf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('troubleshooting_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('defect_draft', sa.JSON(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_summary', sa.JSON(), nullable=True),
    sa.Column('recommended_fix', sa.Text(), nullable=True),
    sa.Column('next_diagnostic_step', sa.Text(), nullable=True),
    sa.Column('candidate_causes', sa.JSON(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troubleshooting_sessions_session_uuid'), 'troubleshooting_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_troubleshooting_sessions_user_id'), 'troubleshooting_sessions', ['user_id'], unique=False)
    op.create_table('troubleshooting_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('selected_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['troubleshooting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troubleshooting_answers_session_id'), 'troubleshooting_answers', ['session_id'], unique=False)
    op.add_column('issues', sa.Column('ai_root_cause_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'troubleshooting_sessions', ['ai_root_cause_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'ai_root_cause_session_id')
    op.drop_index(op.f('ix_troubleshooting_answers_session_id'), table_name='troubleshooting_answers')
    op.drop_table('troubleshooting_answers')
    op.drop_index(op.f('ix_troubleshooting_sessions_user_id'), table_name='troubleshooting_sessions')
    op.drop_index(op.f('ix_troubleshooting_sessions_session_uuid'), table_name='troubleshooting_sessions')
    op.drop_table('troubleshooting_sessions')
    # ### end Alembic commands ###
